# Generated by Django 3.1 on 2020-10-04 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_list', models.TextField(default='', max_length=255)),
                ('year', models.IntegerField(default=1)),
                ('major_1', models.CharField(default='Undecided', max_length=255)),
                ('major_2', models.CharField(default='NONE', max_length=255)),
                ('semester_1', models.TextField(default='', max_length=1000)),
                ('semester_2', models.TextField(default='', max_length=1000)),
                ('semester_3', models.TextField(default='', max_length=1000)),
                ('semester_4', models.TextField(default='', max_length=1000)),
                ('semester_5', models.TextField(default='', max_length=1000)),
                ('semester_6', models.TextField(default='', max_length=1000)),
                ('semester_7', models.TextField(default='', max_length=1000)),
                ('semester_8', models.TextField(default='', max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
