# Generated by Django 3.1 on 2020-08-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discussions_and_Labs',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=4)),
                ('course_num', models.IntegerField()),
                ('class_num', models.IntegerField()),
                ('section_num', models.IntegerField()),
                ('class_type', models.CharField(max_length=10)),
                ('credits', models.IntegerField()),
                ('seat_count', models.IntegerField()),
                ('filled_seats', models.IntegerField(default=0)),
                ('meeting_place', models.CharField(max_length=35)),
                ('professor', models.CharField(max_length=30)),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('date_nums', models.CharField(max_length=10)),
                ('lecture_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=4)),
                ('course_num', models.IntegerField()),
                ('class_num', models.IntegerField()),
                ('section_num', models.IntegerField()),
                ('class_type', models.CharField(max_length=7)),
                ('credits', models.IntegerField()),
                ('seat_count', models.IntegerField()),
                ('filled_seats', models.IntegerField(default=0)),
                ('meeting_place', models.CharField(max_length=35)),
                ('professor', models.CharField(max_length=30)),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('date_nums', models.CharField(max_length=15)),
                ('discussion_lab_nums', models.CharField(max_length=250)),
            ],
        ),
    ]
