# Generated by Django 3.1 on 2020-08-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussions_and_labs',
            name='course_name',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lectures',
            name='course_name',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
