# Generated by Django 3.1 on 2020-08-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200805_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion_or_lab',
            name='date_nums',
        ),
        migrations.AlterField(
            model_name='discussion_or_lab',
            name='end_time',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='discussion_or_lab',
            name='start_time',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='end_time',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='start_time',
            field=models.CharField(max_length=4),
        ),
    ]
