# Generated by Django 3.1 on 2020-08-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200805_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion_or_lab',
            name='date_nums',
            field=models.CharField(default='none', max_length=10),
            preserve_default=False,
        ),
    ]
